apiVersion: neo4j.neo4j.headyj.io/v1alpha1
kind: Grant
metadata:
  annotations:
    meta.upbound.io/example-id: neo4j/v1alpha1/grant
  labels:
    testing.upbound.io/example-name: my_grant
  name: my-grant
spec:
  forProvider:
    action: match
    graph: neo4j
    resource: all_properties
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: my_role

---

apiVersion: neo4j.neo4j.headyj.io/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: neo4j/v1alpha1/grant
  labels:
    testing.upbound.io/example-name: my_role
  name: my-role
spec:
  forProvider:
    name: myRole
