apiVersion: neo4j.headyj.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: neo4j-cluster-creds
      namespace: crossplane-system
      key: credentials
